"""Figures and statistics of the silver labels (entity-category distribution).

Usage:  python -m src.labeling.silver_report      (after build_silver)

Outputs:
  reports/figures/07_entity_label_distribution.png   entity counts per label + % of products per market
  reports/figures/08_label_sources.png                which kind of rule produced each label
  reports/silver_statistics.md
"""
import json
from collections import Counter, defaultdict

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

from src.labeling.bio import LABELS
from src.utils.config import project_path
from src.utils.io import read_jsonl

INK, MUTED, BLUE = "#0b0b0b", "#52514e", "#2a78d6"
GROUPS = ["india", "uk_ireland", "north_america", "other_english"]
# rule families, in a fixed colour order (validated categorical palette)
FAMILIES = [("dictionary (exact)", "#2a78d6"), ("dictionary (in context)", "#86b6ef"),
            ("head-word rule", "#eb6834"), ("regex (INS/E code)", "#1baf7a"), ("fallback", "#c9c7c0")]


def rule_family(rule: str) -> str:
    if rule.startswith("dict:"):
        return "dictionary (exact)"
    if rule.startswith(("dict_suffix", "dict_span", "dict_conj")):
        return "dictionary (in context)"
    if rule.startswith("head:"):
        return "head-word rule"
    if rule.startswith("regex:"):
        return "regex (INS/E code)"
    return "fallback"


def main():
    records = read_jsonl(project_path("data/processed/silver.jsonl.gz"))
    counts = Counter(e["label"] for r in records for e in r["entities"])
    products_with = defaultdict(Counter)
    group_sizes = Counter(r["country_group"] for r in records)
    families = defaultdict(Counter)
    for r in records:
        for label in {e["label"] for e in r["entities"]}:
            products_with[r["country_group"]][label] += 1
        for e in r["entities"]:
            families[e["label"]][rule_family(e["rule"])] += 1

    order = sorted(LABELS, key=lambda l: counts[l])
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(13, 4.8), gridspec_kw={"width_ratios": [1, 1.25]})
    fig.subplots_adjust(wspace=0.45)
    ax1.barh(order, [counts[l] for l in order], color=BLUE, height=0.6)
    ax1.set_xscale("log")
    ax1.set_xlabel("entities in the silver dataset (log scale)")
    ax1.set_title("Silver entities per label", loc="left", color=INK)
    for i, label in enumerate(order):
        ax1.text(counts[label] * 1.1, i, f"{counts[label]:,}", va="center", fontsize=8, color=MUTED)
    ax1.set_xlim(right=max(counts.values()) * 5)

    matrix = pd.DataFrame({g: {l: 100 * products_with[g][l] / group_sizes[g] for l in order[::-1]} for g in GROUPS})
    ax2.imshow(matrix.values, cmap="Blues", vmin=0, vmax=100, aspect="auto")
    ax2.set_xticks(range(len(GROUPS)), GROUPS, fontsize=8)
    ax2.set_yticks(range(len(matrix.index)), matrix.index, fontsize=8)
    for i in range(matrix.shape[0]):
        for j in range(matrix.shape[1]):
            v = matrix.values[i, j]
            ax2.text(j, i, f"{v:.0f}%", ha="center", va="center", fontsize=8, color="white" if v > 55 else INK)
    ax2.set_title("% of products containing the label, by market", loc="left", color=INK)
    ax2.grid(False)
    fig.savefig(project_path("reports/figures/07_entity_label_distribution.png"), dpi=150, bbox_inches="tight")
    plt.close(fig)

    fig, ax = plt.subplots(figsize=(9, 4.8))
    left = pd.Series(0.0, index=order)
    for family, colour in FAMILIES:
        share = pd.Series({l: 100 * families[l][family] / max(1, counts[l]) for l in order})
        ax.barh(order, share, left=left, color=colour, label=family, height=0.6, edgecolor="white", linewidth=1.5)
        left += share
    ax.set_xlim(0, 100)
    ax.set_xlabel("% of the label's silver entities")
    ax.set_title("Which kind of rule produced each label", loc="left", color=INK)
    ax.legend(loc="upper center", bbox_to_anchor=(0.45, -0.13), ncol=5, frameon=False, fontsize=8)
    for side in ("top", "right"):
        ax.spines[side].set_visible(False)
    fig.savefig(project_path("reports/figures/08_label_sources.png"), dpi=150, bbox_inches="tight")
    plt.close(fig)

    log = json.loads(project_path("reports/silver_log.json").read_text(encoding="utf-8"))
    lines = ["# Silver dataset statistics (auto-generated by `python -m src.labeling.silver_report`)", "",
             "SILVER = produced automatically by dictionaries and rules. Not ground truth.", "",
             f"* Records: {log['records_out']:,} (skipped: {log['skipped']})",
             f"* Tokens: {log['tokens']:,}; tagged O: {log['tokens_tagged_O_percent']}%",
             f"* Entities: {log['entities']:,}", "",
             "| Label | Entities | % of products |", "|---|---:|---:|"]
    for label in order[::-1]:
        share = 100 * sum(products_with[g][label] for g in GROUPS) / len(records)
        lines.append(f"| {label} | {counts[label]:,} | {share:.1f}% |")
    lines += ["", "![labels](figures/07_entity_label_distribution.png)", "",
              "![sources](figures/08_label_sources.png)", ""]
    project_path("reports/silver_statistics.md").write_text("\n".join(lines), encoding="utf-8")
    print("Saved figures 07, 08 and reports/silver_statistics.md")


if __name__ == "__main__":
    main()
